### PR TITLE
Fix most visited page not hiding chrome initial startup

### PR DESCRIPTION
**Pull request by christianesperar**

### CODE REVIEW

**Comment by mkx64** [comment]
Will check this out tomorrow and see if it does not throw any errors. If it works, I merge it and publish it to the Chrome WebStore and mention you in the about sections :)

**Comment by mkx64** [comment]
Does not work in Chromium 48.0.2564.82 (64-bit) Linux Can't merge in, sorry.

**Comment by christianesperar** [comment]
May I know the error, it's working on my end.

**Comment by mkx64** [comment]
`Error in response to tabs.query: TypeError: Cannot read property 'url' of undefined
    at Object.callback (background.js:3:16)
    at processTabAction (background.js:2:15)
    at handleTabUrlChange (background.js:10:3)
    at background.js:14:1
handler	@	extensions::uncaught_exception_handler:8
(anonymous function)	@	extensions::uncaught_exception_handler:100
safeCallbackApply	@	extensions::sendRequest:23
handleResponse	@	extensions::sendRequest:72`

**Pull request closed without merging**
